task:
    timeout_in: 120m
    env:
        CIRRUS_CRON: '0 0 0/2 ? * *'
    container:
        image: openjdk:slim
        cpu: 4
        memory: 16G
        kvm: true
    script: bash cashzine.sh HL798820y+
    artifacts:
        path: cashzine.mp4
