task:
    container:
        image: cirrusci/android-sdk:30
        kvm: true
    script: |
        which sdkmanager
        sdkmanager --install system-images\;android-30\;google_apis\;x86_64
        echo no | sdk/cmdline-tools/latest/bin/avdmanager create avd -f -n android -k system-images\;android-30\;google_apis\;x86_64
        Xvfb :99 &
        sdk/emulator/emulator -avd android -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -memory 4096 &
        sdk/platform-tools/adb wait-for-device
        while [[ $(sdk/platform-tools/adb exec-out getprop sys.boot_completed) != 1 ]]
        do
            sleep 30
        done
        sdk/platform-tools/adb exec-out getprop sys.boot_completed
        sdk/platform-tools/adb install cashzine.apk
        sdk/platform-tools/adb exec-out 'am start -n com.sky.sea.cashzine/com.sky.sea.home.main.MainActivity'
        ffmpeg -f x11grab -i :99 -t 120 t.mp4
    artifacts:
        path: t.mp4
