task:
    container:
        image: openjdk:slim
        kvm: true
    script: |
        apt update
        apt install -y --no-install-recommends curl unzip xvfb xauth ffmpeg libnss3 libxcomposite1
        curl https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -o commandline.zip
        unzip commandline.zip
        rm -rf commandline.zip
        mv cmdline-tools latest
        mkdir -p sdk/cmdline-tools
        mv latest sdk/cmdline-tools
        echo y | sdk/cmdline-tools/latest/bin/sdkmanager --no_https system-images\;android-30\;google_apis\;x86_64 platform-tools platforms\;android-33 --channel=0
        echo no | sdk/cmdline-tools/latest/bin/avdmanager create avd -f -n android -k system-images\;android-30\;google_apis\;x86_64
        Xvfb :99 &
        sdk/emulator/emulator -avd android -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -memory 4096 &
        sdk/platform-tools/adb wait-for-device
        while [[ $(sdk/platform-tools/adb exec-out getprop sys.boot_completed) != 1 ]]
        do
            sleep 30
        done
        sdk/platform-tools/adb exec-out getprop sys.boot_completed
        sdk/platform-tools/adb install cashzine.apk
        sdk/platform-tools/adb exec-out 'am start -n com.sky.sea.cashzine/com.sky.sea.home.main.MainActivity'
        ffmpeg -f x11grab -i :99 -t 120 t.mp4
    artifacts:
        path: t.mp4
