cashzine_task:
    timeout_in: 120m
    container:
        image: openjdk:slim
        cpu: 4
        memory: 16G
        kvm: true
    env:
        password: ENCRYPTED[d71511f1e01c0539cf340cd0b5093351e19e01f5d0cf6054ed0ae1d5133b3ff6ca974d03309f643ec03f5fae5177efa3]
    script: |
        apt update
        apt install -y --no-install-recommends curl
        curl -O https://bitbucket.org/chaowenguo/android/raw/main/cashzine.sh
        bash cashzine.sh $password
        #curl https://bitbucket.org/chaowenguo/android/raw/main/cashzine.sh | bash -s -- $password
    artifacts:
        path: cashzine.mp4

modeEarn_task:
    timeout_in: 120m
    container:
        image: openjdk:slim
        cpu: 4
        memory: 16G
        kvm: true
    env:
        password: ENCRYPTED[d71511f1e01c0539cf340cd0b5093351e19e01f5d0cf6054ed0ae1d5133b3ff6ca974d03309f643ec03f5fae5177efa3]
    script: |
        apt update
        apt install -y --no-install-recommends curl
        curl -O https://bitbucket.org/chaowenguo/android/raw/main/modeEarn.sh
        bash modeEarn.sh $password
    artifacts:
        path: modeEarn.mp4
