task:
    timeout_in: 120m
    container:
        image: openjdk:slim
        cpu: 4
        memory: 16G
        kvm: true
    script: bash cashzine.sh HL798820y+
    artifacts:
        path: cashzine.mp4
