task:
    container:
        image: cirrusci/android-sdk:30
        kvm: true
    script: |
        apt update
        DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends xvfb xauth xorg
        echo y | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --install system-images\;android-30\;google_apis\;x86_64
        echo no | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -f -n android -k system-images\;android-30\;google_apis\;x86_64
        Xvfb :99 &
        $ANDROID_HOME/emulator/emulator -avd android -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -memory 4096 &
        $ANDROID_HOME/platform-tools/adb wait-for-device
        while [[ $($ANDROID_HOME/platform-tools/adb exec-out getprop sys.boot_completed) != 1 ]]
        do
            sleep 30
        done
        $ANDROID_HOME/platform-tools/adb exec-out getprop sys.boot_completed
        $ANDROID_HOME/platform-tools/adb install cashzine.apk
        $ANDROID_HOME/platform-tools/adb exec-out 'am start -n com.sky.sea.cashzine/com.sky.sea.home.main.MainActivity'
        ffmpeg -f x11grab -i :99 -t 120 t.mp4
    artifacts:
        path: t.mp4
